config/routes.rb
Rails.application.routes.draw do
  resources :dishes

  devise_for :users
  root "pages#home"
  get "about" => "pages#about"
  get "contact-us", to: "pages#contact_us", as: "contact-us"

end

app/models/dish.rb
class Dish < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => {medium: "300x300>", thumb: "100x100>"}, :default_url => "default_dish.png"

#In Paperclip 4.0+ must validate content type or explicity state that no validation is required
	validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	validates :name, :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :dishes, dependent: :destroy

  validates :firstName, :lastName, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # 
  before_filter :configure_permitted_parameters, if: :devise_controller?
 protected
 def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :firstName, :lastName, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :firstName, :lastName, :email, :password, :password_confirmation, :current_password) }
end 
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all.order("created_at DESC").paginate(page: params[:page], per_page: "4")
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = current_user.dishes.build
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = current_user.dishes.build(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish added successfully!' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Prevent users from accessing edit functionality via URLs
    def correct_user
      if current_user
        @dish = current_user.dishes.find_by(id: params[:id])
        redirect_to dishes_path, notice: "You are not authorized to make changes to that dish" if @dish.nil?
      else
        redirect_to new_user_session_path, notice: "Please sign in to continue."
      end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:name, :description, :image)

    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@disable_primary_container = true
  	@disable_navbar = true
  end

  def about
  end

  def contact_us
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/dishes/_form.html.erb
<%= form_for @dish, html: { multipart: true } do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <div><%= f.file_field :image, class: "form-control"%></div>  
  <div><%= f.text_field :name, class: "form-control", placeholder: "Name" %></div>
  <div><%= f.text_field :description, class: "form-control", placeholder: "Tell people about this dish" %></div>
</div>

<!--If page is asking user to edit content, show different button -->
<% if current_page?(controller: 'dishes', action: "new") %>
  <div><%= f.submit "Create Dish", class: "btn btn-large sign-up" %></div>
<% elsif current_page?(controller: 'dishes', action: "edit") %>
  <div><%= f.submit "Save Changes", class: "btn btn-large sign-up" %></div>
<% end %>
<% end %>

app/views/dishes/edit.html.erb
<%= link_to 'Back', dishes_path %>
<div class="panel panel-default sessions">
	<div class="center">
		<font color="#34495e"><h3>Edit Your Dish</h3></font>
			
		<%= image_tag @dish.image.url(:medium) %>
		<%= render 'form' %>

		<%= link_to 'Show', @dish %> |
		<%= link_to 'Back', dishes_path %>
	</div><!-- .center -->
</div><!-- panel.panel-default.sessions -->

app/views/dishes/index.html.erb
<%= form_tag do %>
< This will be where people can decide how many dishes will be visible per page >
<% end %>
<div id="dishes">
  <% @dishes.each do |dish| %>
  <div class="box animated fadeInUp">
    <div class="boxTitle">
      <%= dish.name %>
    </div>

    <%= link_to( image_tag(dish.image.url(:medium)), dish)%>
    
    <% if dish.user && dish.user.firstName %>
    
      <div class="boxMeta">
        <%= dish.description %>
      </div> <!-- .boxMeta -->

      <% if current_user && dish.user == current_user %>
      
        <div class="boxCredits">
          Created by: <%= dish.user.firstName %>
          <% if dish.user.lastName %>
            <%= dish.user.lastName[0] %>.
          <% end %>
        </div> <!-- .boxCredits -->

        <div class="boxOptions">
          <%= link_to edit_dish_path(dish) do %>
            <span class="glyphicon glyphicon-pencil"></span> Edit
          <% end %>

          <%= link_to dish, method: :delete, data: { confirm: 'Are you sure you want to delte this dish? You cannot undo this action.'} do %>
            <span class="glyphicon glyphicon-trash"></span> Delete
          <% end %>
        </div> <!-- .boxOptions -->
      
      <% else %>

        <div class="boxCredits noOptions">
          Created by: <%= dish.user.firstName %>
          <% if dish.user.lastName %>
            <%= dish.user.lastName[0] %>.
          <% end %>
        </div> <!-- .boxCredits noOptions -->

      <% end %>

    <% else %>

      <div class="boxMeta noCredits">
        <%= dish.description %>
      </div> <!-- .boxMeta.no-user -->
    
    <% end %>

  </div> <!-- .box.animated.fadeInUp-->
<% end %> <!-- @dishes do -->
</div>!<!-- #dishes -->

<div class="center animated fadeIn">
  <%= will_paginate @dishes, renderer: BootstrapPagination::Rails %>
</div>

app/views/dishes/new.html.erb
<div class="panel panel-default sessions">
	<div class="center">
		<font color="#34495e"><h3 class="animated bounceInDown">Create a Dish</h3></font>

		<%= render 'form' %>

		<%= link_to 'Back', dishes_path %>
	</div><!-- .center-->
</div><!-- .panel.panel-default.sessions -->

app/views/dishes/show.html.erb
<%= link_to 'Back', dishes_path %>

<div class ="box">

	<div class="boxTitle">
		<%= @dish.name %>
	</div><!-- .boxTitle -->

	<%= image_tag @dish.image.url(:medium)%>

    <% if @dish.user && @dish.user.firstName %>
    
      <div class="boxMeta">
        <%= @dish.description %>
      </div> <!-- .boxMeta -->

      <% if current_user && @dish.user == current_user %>
      
        <div class="boxCredits">
          Created by: <%= @dish.user.firstName %>
          <% if @dish.user.lastName %>
            <%= @dish.user.lastName[0] %>.
          <% end %>
        </div> <!-- .boxCredits -->

        <div class="boxOptions">
          <%= link_to edit_dish_path(@dish) do %>
            <span class="glyphicon glyphicon-pencil"></span> Edit
          <% end %>

          <%= link_to @dish, method: :delete, data: { confirm: 'Are you sure you want to delte this dish? You cannot undo this action.'} do %>
            <span class="glyphicon glyphicon-trash"></span> Delete
          <% end %>
        </div> <!-- .boxOptions -->
      
      <% else %>

        <div class="boxCredits noOptions">
          Created by: <%= @dish.user.firstName %>
          <% if @dish.user.lastName %>
            <%= @dish.user.lastName[0] %>.
          <% end %>
        </div> <!-- .boxCredits noOptions -->

      <% end %>

    <% else %>

      <div class="boxMeta noCredits">
        <%= @dish.description %>
      </div> <!-- .boxMeta.no-user -->
    
    <% end %>

</div><!-- .box -->

app/views/layouts/_footer.html.erb
<div id="footer">
	<div class="container">
		<div class="row">
			<p><strong>THIS FOOTER STILL NEEDS TO BE FIXED!</strong></p>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Delishus", root_path, :class=>"navbar-brand"%>

      </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "About Us", about_path%>
        </li>
        <li>
          <%= link_to "Contact Us", contact_us_path%>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Browse Dishes", dishes_path %>
        </li>
          <% if user_signed_in? %>
          <li>
            <%= link_to new_dish_path do %>
              <span class="glyphicon glyphicon-cutlery"></span> Add a Dish
            <% end %>
          </li>
        </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hello <%= current_user.firstName  %>!<b class="caret"></b></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <%= link_to edit_user_registration_path, align: "right" do %>
                    Account Settings <span class="glyphicon glyphicon-cog"></span>
                  <% end %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to destroy_user_session_path, align: "right", method: :delete do %>
                    Log Out <span class="glyphicon glyphicon-log-out"></span>
                  <% end %>
                </li>
              </ul>
          <% elsif !user_signed_in? %>
            <li><%=link_to "Log In", new_user_session_path, align: "right" %></li>
          <% end %>
        </li><!-- /dropdown -->
      </ul>
    </div><!-- .navbar-collapse -->
  </div><!-- .container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	

  <title>Delish.us</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%- #Enable responsiveness on mobile devices -%>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%- #Add animate.css -%>
  <link rel="stylesheet" href="animate.min.css">

</head>

<body>
  	<%= render 'layouts/header' unless @disable_navbar %>
    <!-- Check if primary container should be disabled to allow full-screen carousel -->
    <% if @disable_primary_container %>
      <%= yield %>
    <% else %>
      <div class="container">
        <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>
        <%= yield %>
      </div>  
    <% end %>
<!-- <%= render 'layouts/footer'%> -->
</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
	<p>This is a work in progress by <%= link_to "Michael Ottavi-Brannon", "http://www.facebook.com/mottavibrannon", :target => "_blank"%>.</p>

app/views/pages/contact_us.html.erb
<h1>Contact Us</h1>	
	<p>Need help?  Get in touch!</p>

app/views/pages/home.html.erb
<!-- NAVBAR -->
  <div class="nav navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Delishus", root_path, :class=>"navbar-brand"%>

          </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "About Us", about_path%>
            </li>
            <li>
              <%= link_to "Contact Us", contact_us_path%>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to "Browse Dishes", dishes_path %>
            </li>
              <% if user_signed_in? %>
              <li>
                <%= link_to new_dish_path do %>
                  <span class="glyphicon glyphicon-cutlery"></span>  Add a Dish
                <% end %>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hello <%= current_user.firstName %>!<b class="caret"></b></a>
                  <ul class="dropdown-menu dropdown-menu-right">
                    <li>
                      <%= link_to edit_user_registration_path, align: "right" do %>
                        Account Settings <span class="glyphicon glyphicon-cog"></span>
                      <% end %>
                    </li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to destroy_user_session_path, align: "right", method: :delete do %>
                        Log Out <span class="glyphicon glyphicon-log-out"></span>
                      <% end %>
                    </li>
                  </ul>
              <% elsif !user_signed_in? %>
                <li><%=link_to "Log In", new_user_session_path, align: "right" %></li>
              <% end %>
            </li><!-- /dropdown -->
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </div><!-- .container -->
  </div><!-- .nav.navbar-defautl.navbar-fixed -->

  <!-- FLASH MESSAGES -->
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>

  <!-- JQUERY CODE TO FADE ALERTS -->
    <script type="text/javascript">

      $(function() {
        $('.alert.alert-info')
        .delay(3000)
        .fadeOut(function() {
          $(this).remove();
        })
      })
    </script>
  
  </div><!-- /.container -->


<!-- CAROUSEL -->
<div id="homeCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#homeCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#homeCarousel" data-slide-to="1"></li>
    <li data-target="#homeCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    
    <div class="item active">
      <%= image_tag("cheeseBoard.jpg", :alt=>"Cheese Board") %> 
      <div class="container">
        <div class="carousel-caption">
          <h1>Welcome to Delishus</h1>
          <p>Delishus is the easiest way to find and discover great food around you</p>
          <p>
            
             <% if user_signed_in? %>
              <%= link_to "Browse Dishes", dishes_path, class: "btn btn-large btn-primary" %>
            <% elsif %>
              <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-large btn-primary  "%>
            <% end %>

          </p>
        </div><!-- /.carousel-caption -->
      </div><!-- /.container -->
    </div><!-- /.item active-->

    <div class="item">
      <%= image_tag("moscowMule.jpg", :alt=>"Moscow Mule") %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Explore</h1>
          <p>Discover new favorites at restaurants new and old </p>
          <p>

            <% if user_signed_in? %>
              <%= link_to "Browse Dishes", dishes_path, class: "btn btn-large btn-primary" %>
            <% elsif %>
              <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-large btn-primary  "%>
            <% end %>

          </p>  
        </div><!-- /.carousel-caption -->
      </div><!-- /.container -->
    </div><!-- /.item -->
    
    <div class="item">
      <%= image_tag("dinnerTable.jpeg", :alt=>"Dinner Table") %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Just for You</h1>
          <p>Delishus works with you to learn about your tastes and make sure that every time you dine out, you order a meal you'll love</p>
          
          <p>
           <% if user_signed_in? %>
              <%= link_to "Browse Dishes", dishes_path, class: "btn btn-large btn-primary" %>
          <% else %>
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-large btn-primary  "%>
          <% end %>
          </p>

        </div><!-- /.carousel-caption -->
      </div><!-- /.container -->
    </div><!-- /.item -->

  </div><!-- /.carousel-inner -->



  <a class="left carousel-control" href="#homeCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#homeCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>

</div>

<!--CUSTOM MARKETING CONTAINER-->

<div class="container marketing">
  <div class="center">
    <h2>Meet the Team</h2>
  </div>
  <div class="marketing_images row">
    <div class="col-lg-6">
      <%= image_tag("Michael.jpg", alt: "Michael Ottavi-Brannon", class: "img-circle") %>
      <h2>Michael Ottavi-Brannon</h2>
      <p>Likes Bacon</p>
    </div>
    <div class="col-lg-6">
      <%= image_tag("Evan.jpg", :alt=>"Evan Hyde", :class=>"img-circle") %>
      <h2>Evan Hyde</h2>
      <p>Likes Bloody Marys</p>
    </div>
  </div><!-- /.row-->

  <hr class="featurette-divider">

  <!--CUSTOM MIDDLE CONTAINER-->
  <div class="row featurette">
    <div class="col-lg-8">
        <h1>Built Just for You</h1>
        <p>Restaurant menus can be confusing and overwhelming. Let Delishus help you find the meals you'll love</p>
    </div><!-- /.col-lg-8 -->  
  </div><!-- /.row featurette -->

  <hr class="featurette-divider">

  <!--CUSTOM MIDDLE CONTAINER-->
  <div class="row featurette">
    <div class="col-lg-8 col-lg-offset-4">
      <h1>In the Moment</h1>
      <p>What other kind of cool and creative marketing content can you come up with?</p>
    </div><!-- /.col-lg-8 -->
  </div><!-- /.row featurette -->
</div><!-- /.container marketing-->